### ISSUE TITLE
where is Lidar.hpp?

### ISSUE THREAD

**Issue by Tsejing** [Club-INTech/TIM561#1]
TIM561-master/lidar/include/TIM561.h:19:30: fatal error: ../../../Lidar.hpp: No such file or directory
compilation terminated.
CMakeFiles/TIM561.dir/build.make:62: recipe for target 'CMakeFiles/TIM561.dir/main.cpp.o' failed

when I run make,there is an error as above,Looking forward for your reply,thanks!

**Comment by juliandesvignes** [comment]
This project is unsuited for standalone use, this is part of a much bigger project that has a very specific use case and layout (French Robotics Cup). If you want to use the core code of this library, I do recommend you to start your own library using functions and code bits of this project. Sorry for the inconvenience.

**Comment by Tsejing** [comment]
ok,thanks.I just want to use functions and code bits of this project and the problem has been solved.Thanks for your reply again.


 
---Original---
